---
- name: Wait for ssh connection
  hosts: ansible-webserver
  gather_facts: False
  tasks:
    - name: Ensure ssh port open
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

- name: Install Docker
  hosts: ansible-webserver
  become: yes
  gather_facts: true
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python3
        docker_host: unix://var/run/docker.sock  # Specify Docker host
      ansible.builtin.apt:
        name: 
          - python3
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Install docker python module
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose

- name: Add ubuntu user to docker group
  hosts: ansible-webserver
  become: yes
  tasks:
    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Reconnect to server session
      ansible.builtin.meta: reset_connection

- name: Create a new user
  become: yes
  hosts: webserver
  roles:
    - create_user

- name: Start docker containers
  hosts: ansible-webserver
  roles:
    - start_containers
