---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy nginx app
      k8s:
        src: /Users/pro/Documents/devops/k8s-administrator-course/03-Deploy-Application/nginx-deployment.yaml
        state: present
        namespace: my-app